### ISSUE TITLE
Crash On iPad

### ISSUE THREAD

**Issue by waitTinyxx** [music4kid/AirSandbox#1]
The Reason of Crash:(<_UIAlertControllerActionSheetRegularPresentationController: 0x154dbb9b0>) should have a non-nil sourceView or barButtonItem set before the presentation occurs.

should add codes in function :- (void)sharePath:(NSString*)path like this:

    if ([[UIDevice currentDevice].model isEqualToString:@"iPad"]) {
        controller.popoverPresentationController.sourceView = self.view;
        controller.popoverPresentationController.sourceRect = CGRectMake([UIScreen mainScreen].bounds.size.width * 0.5, [UIScreen mainScreen].bounds.size.height, 10, 10);
    }

**Comment by music4kid** [comment]
just fixed it, thanks ;)
